#ifndef WHEELCHAIR_CONFIG_HPP
#define WHEELCHAIR_CONFIG_HPP

#define i2c_Address 0x3c
// #define SCL_PIN GPIO_NUM_9
// #define SDA_PIN GPIO_NUM_8

#define SDA_PIN GPIO_NUM_8
#define SCL_PIN GPIO_NUM_10

#endif // WHEELCHAIR_CONFIG_HPP